version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      #dockerfile: Dockerfile.python2
      #dockerfile: Dockerfile.python3
    ports:
      - "8080:8080"
    command: bash -c 'python app.py | tee --append /logs/production.log'
    volumes:
      - /volumes/bottle-wiki/logs:/logs
